export default {
  GET_NOTIFICATIONS: "GET_NOTIFICATIONS_SUCCESS",
  ADD_NOTIFICATION: "ADD_NOTIFICATION",
  READ_ALL_NOTIFICATIONS: "READ_ALL_NOTIFICATIONS",
  DELETE_SINGLE_NOTIFICATION: "DELETE_SINGLE_NOTIFICATION",
  DELETE_NOTIFICATIONS: "DELETE_NOTIFICATIONS",
  NOTIFICATION_ACTION_FAIL: "NOTIFICATION_ACTION_FAIL",
};
