export default {
  LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  SIGN_OUT_USER_SUCCESS: "SIGN_OUT_USER_SUCCESS",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  SET_LOADING: "SET_LOADING",
};
